# Regexes which if matched by a file path will always be excluded from
# getting a license header
excludes:
  - \.gitignore
  - .*lock
  - \.github/.*
  - \.vscode/.*
  - \.cargo/.*
  - \.git/.*
  - \.rpm/.*
  - \.licensure\.yml
  - \.editorconfig
  - README.*
  - LICENSE.*
  - COPYING
  - gtksourceview-5
  - package
  - target
  - libs
  - docker-*.yml
  - data
  - setup.iss
  - .*\.(md|rst|txt|iss|desktop|svg|toml)
change_in_place: true

licenses:
  - files: any
    ident: GPL-3.0
    unwrap_text: false
    authors:
      - name: Miguel A. Baldi Hörlle
        email: miguel.horlle@gmail.com
    template: |
      Copyright (c) [year], [name of author]. All rights reserved. Use of
      this source code is governed by the [ident] license that can be
      found in the COPYING file.

# Define type of comment characters to apply based on file extensions.
comments:
  # The extensions (or singular extension) field defines which file
  # extensions to apply the commenter to.
  - extensions:
      - rs
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - extensions:
      - css
      - cpp
      - c
      - less
    commenter:
      type: block
      start_block_char: "/*\n"
      end_block_char: "*/"
      per_line_char: "*"
      trailing_lines: 1
  - extension: any
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1
