# Copyright (c) 2024, Miguel A. Baldi Hörlle <miguel.horlle@gmail.com>. All rights reserved. Use of
# this source code is governed by the GPL-3.0 license that can be
# found in the COPYING file.

services:
  krust-deb-build:
    image: ubuntu:25.04
    volumes:
      - .:/mnt:z
    command: bash -c "cd /mnt && ./build-scripts/linux-deb-prepare-and-build.sh"
