name: Build and publish

on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker-compose up
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: executables
        if-no-files-found: error
        path: |
          target/appimage/*.AppImage
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build (Windows)
      run: docker-compose -f docker-compose.windows.yml up
    - name: Make Windows Installer
      run: ./create_windows_installer.sh
    - name: Zip Portable Windows Artifact
      run: zip -r windows-portable.zip package
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: |
          *.zip
          *.exe

  publish:
    permissions:
      contents: write
    needs: [build, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v2
    - uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: false
        generate_release_notes: true
        files: |
          **/*.AppImage
          **/*.zip
          **/*.exe
